apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
  labels:
    app: kktomcat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kktomcat
  template:
    metadata:
      labels:
        app: kktomcat
    spec:
      containers:
      - name: kktomcat
        image: kranthigk27/kktomcat:latest
        ports:
        - containerPort: 8080
